---

- lineinfile: dest=/etc/sysctl.conf regexp="net.ipv4.conf.all.rp_filter" line="net.ipv4.conf.all.rp_filter=0"
- lineinfile: dest=/etc/sysctl.conf regexp="net.ipv4.conf.default.rp_filter" line="net.ipv4.conf.default.rp_filter=0"

- command: sysctl -p


- template: src=l3_agent.ini.j2 dest=/etc/neutron/l3_agent.ini owner={{ user_name }} group={{ group_name}}

- template: src=dhcp_agent.ini.j2 dest=/etc/neutron/dhcp_agent.ini owner={{ user_name }} group={{ group_name}}

- template: src=dnsmasq-neutron.conf.j2 dest=/etc/neutron/dnsmasq-neutron.conf owner={{ user_name }} group={{ group_name}}

- template: src=metadata_agent.ini.j2 dest=/etc/neutron/metadata_agent.ini owner={{ user_name }} group={{ group_name}}
