---

- file: path={{ deploy_dir }} state=directory

- synchronize: src={{ source_dir }}/neutron dest={{ deploy_dir }} mode=push

- shell: pip install {{ item }} --no-allow-insecure
  with_lines: python /etc/ansible/facts.d/get-requirements.py {{ deploy_dir }}/neutron

- shell: pip install -e {{ deploy_dir }}/neutron --no-allow-insecure

- file: path={{ item }} state=directory owner={{ user_name }} group={{ group_name }}
  with_items:
    - /etc/neutron
    - /var/log/neutron

- copy: src={{ deploy_dir }}/neutron/etc/{{ item }} dest=/etc/neutron/
  with_items:
    - neutron.conf
    - api-paste.ini
    - dhcp_agent.ini
    - l3_agent.ini
    - metadata_agent.ini
    - metering_agent.ini
    - policy.json
    - rootwrap.conf

- copy: src={{ deploy_dir }}/neutron/etc/neutron/{{ item }} dest=/etc/neutron/
  with_items:
    - plugins
    - rootwrap.d

- template: src=neutron.conf.j2 dest=/etc/neutron/neutron.conf owner={{ user_name }} group={{ group_name}}

- template: src=ml2_conf.ini.j2 dest=/etc/neutron/plugins/ml2/ml2_conf.ini owner={{ user_name }} group={{ group_name}}

- file: src=/etc/neutron/plugins/ml2/ml2_conf.ini dest=/etc/neutron/plugin.ini state=link
#- command: ln -s /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini
#  ignore_errors: True


- include: controller.yml
  when: >
    inventory_hostname in groups['controllers']

- include: network.yml
  when: >
    inventory_hostname in groups['networks']
