---

- include: command.yml
  vars:
    get_command: openstack service show identity
    create_command: openstack service create --name keystone --description "OpenStack Identity" identity

- include: command.yml
  vars:
    get_command: openstack endpoint show identity
    create_command: openstack endpoint create --publicurl "{{ keystone_service_url }}" --adminurl "{{ keystone_admin_url }}" --internalurl "{{ keystone_service_url }}" --region RegionOne identity

- include: command.yml
  vars:
    get_command: openstack project show admin
    create_command: openstack project create --description "Admin Project" admin

- include: command.yml
  vars:
    get_command: openstack user show admin
    create_command: openstack user create --password {{ admin_password }} admin

- include: command.yml
  vars:
    get_command: openstack role show admin
    create_command: openstack role create admin

- include: command.yml
  vars:
    get_command: openstack user role list --project admin admin
    create_command: openstack role add --project admin --user admin admin

- include: command.yml
  vars:
    get_command: openstack project show service
    create_command: openstack project create --description "Service Project" service

- include: command.yml
  vars:
    get_command: openstack project show demo
    create_command: openstack project create --description "Demo Project" demo


- include: command.yml
  vars:
    get_command: openstack user show demo
    create_command: openstack user create --password {{ demo_password }} demo

- include: command.yml
  vars:
    get_command: openstack role show user
    create_command: openstack role create user

- include: command.yml
  vars:
    get_command: openstack user role list --project demo demo
    create_command: openstack role add --project demo --user demo user
