---

- file: path={{ deploy_dir }} state=directory

- synchronize: src={{ source_dir }}/nova dest={{ deploy_dir }}
  delegate_to: localhost

- shell: pip install {{ item }} --no-allow-insecure
  with_lines: python /etc/ansible/facts.d/get-requirements.py {{ deploy_dir }}/nova
