---

- file: path={{ deploy_dir }} state=directory

- synchronize: src={{ source_dir }}/nova dest={{ deploy_dir }} mode=push

- shell: pip install {{ item }} --no-allow-insecure
  with_lines: python /etc/ansible/facts.d/get-requirements.py {{ deploy_dir }}/nova

# bugfix: jsonschema depends on functools32
- shell: pip install functools32 --no-allow-insecure

- shell: pip install -e {{ deploy_dir }}/nova --no-allow-insecure

- file: path={{ item }} state=directory owner={{ user_name }} group={{ group_name }}
  with_items:
    - /etc/nova
    - /var/log/nova
    - /var/lock/nova
    - /usr/share/novnc

- copy: src={{ deploy_dir }}/nova/etc/nova/{{ item }} dest=/etc/nova/{{ item.replace('.sample', '').replace('_sample', '') }}
  with_items:
    - api-paste.ini
    - cells.json
    - logging_sample.conf
    - policy.json
    - rootwrap.conf

- copy: src={{ deploy_dir }}/nova/etc/nova/rootwrap.d dest=/etc/nova/

- template: src=nova.conf.j2 dest=/etc/nova/nova.conf owner={{ user_name }} group={{ group_name}}


- include: controller.yml
  when: >
    inventory_hostname in groups['controllers']

- include: compute.yml
  when: >
    inventory_hostname in groups['computes']
