---

- hosts: all

  tasks:
  - file: path={{ deploy_dir }} state=directory

  - synchronize: src={{ source_dir }}/{{ item }} dest={{ deploy_dir }} mode=push
    with_items: clients


  - shell: pip install -e {{ deploy_dir }}/{{ item }} --no-allow-insecure
    with_items: clients


  vars_files:
      - vars/openstack.yml

  vars:
    clients:
      - python-keystoneclient
      - python-cinderclient
      - python-glanceclient
      - python-neutronclient
      - python-novaclient
      - python-swiftclient
      - python-openstackclient
