---

- name: Setup glance
  hosts: controller

  pre_tasks:
    - include: setup-users.yml

  roles:
    - glance

    - { role: supervisor, name: glance, programs: [
      {name: glance-api, cmdline: "{{ virtualenv_dir }}/bin/glance-api"},
      {name: glance-registry, cmdline: "{{ virtualenv_dir }}/bin/glance-registry"}]}

  vars_files:
    - vars/openstack.yml
    - vars/secrets.yml

  vars:
    user_name: glance
    group_name: glance
