---

- name: Setup glance
  hosts: controller

  pre_tasks:
    - include: setup-users.yml

  roles:
    - glance

  vars_files:
    - vars/openstack.yml
    - vars/secrets.yml

  vars:
    user_name: glance
    group_name: glance
