---

- name: Setup keystone
  hosts: controller

  pre_tasks:
    - include: setup-users.yml

  roles:
    - keystone

    - { role: supervisor, name: keystone,
        programs: [
          {name: keystone-all, cmdline: "{{ virtualenv_dir }}/bin/keystone-all"}
        ]
      }

  post_tasks:
    - include: roles/keystone/tasks/identity.yml

  vars_files:
    - vars/openstack.yml
    - vars/secrets.yml

  vars:
    user_name: keystone
    group_name: keystone
