---

- name: Setup MySQL
  hosts: controller
  user: root
  tasks:
    - name: Install MySQL
      yum: name={{ item }} state=present
      with_items:
        - mariadb
        - mariadb-server
        # The Python MySQL library is compatible with MariaDB
        - MySQL-python

    # Setup MySQL configuration file /etc/my.cnf
    - ini_file: dest=/etc/my.cnf section=mysqld option=bind-address value={{ ansible_default_ipv4.address }}
    - ini_file: dest=/etc/my.cnf section=mysqld option=default-storage-engine value=innodb
    - ini_file: dest=/etc/my.cnf section=mysqld option=innodb_file_per_table value=1
    - ini_file: dest=/etc/my.cnf section=mysqld option=collation-server value=utf8_general_ci
    - ini_file: dest=/etc/my.cnf section=mysqld option=init-connect value="'SET NAMES utf8'"
    - ini_file: dest=/etc/my.cnf section=mysqld option=character-set-server value=utf8

    - name: Enable and restart MySQL
      service: name=marialdb enabled=yes state=restarted
