---

- name: Setup networking
  hosts: all

  tasks:

      - include: install-facts.yml

      - debug: msg={{ item.key}}:{{item.value}}
        with_dict: ansible_local.dynamic.host

      - shell: grep GATEWAY {{ ifcfg_file }}{{ hostvars['controller']['ansible_default_ipv4']['interface'] }}
        register: gateway
        delegate_to: controller
      - debug: var=ansible_env.SSH_CONNECTION.split()[2]
#      - shell: grep GATEWAY {{ ifcfg_file }}
#        register: result
#        ignore_errors: True
#      - lineinfile: dest={{ ifcfg_file }} line={{ ansible_default_ipv4.gateway }}
#        when: result|failed

  vars:
    ifcfg_file: /etc/sysconfig/network-scripts/ifcfg-
