---

- name: Setup networking
  hosts: all

  tasks:

      - include: install-facts.yml

#      - debug: msg={{ item.key}}:{{item.value}}
#        with_dict: ansible_local.dynamic.host

      - shell: grep GATEWAY {{ ifcfg_file }}{{ hostvars['controller']['ansible_default_ipv4']['interface'] }}
        register: gateway
        delegate_to: controller
        when: ansible_hostname != 'controller'

      - lineinfile: dest={{ ifcfg_file }}{{ansible_local.dynamic.host.interface}} regexp=GATEWAY line={{ gateway.stdout }}
        when: ansible_hostname != 'controller'

      - shell: ifdown {{ansible_local.dynamic.host.interface}} && ifup {{ansible_local.dynamic.host.interface}}
        when: ansible_hostname != 'controller'

  vars:
    ifcfg_file: /etc/sysconfig/network-scripts/ifcfg-
