---

- name: Setup keystone
  hosts: controller

  pre_tasks:
    - include: setup-users.yml user_name=keystone group_name=keystone

  roles:
    - keystone

  vars_files:
    - vars/openstack.yml
    - vars/secrets.yml
