---

- name: Upgrade packages
  hosts: all
  tasks:
    - name: Upgrade packages
      yum: name=* state=latest
      when: upgrade is defined


- hosts: all
  tasks:
    - yum: name={{ item }} state=present
      with_items: install_packages

    - lineinfile: dest=/etc/sudoers regexp='#?(Defaults.+requiretty)' line='#\1' backrefs=yes
    - template: src=roles/supervisor/templates/supervisord.conf.j2 dest=/etc/supervisord.conf

    - service: name={{ item }} enabled=yes state=started
      with_items: autostart_services

  vars:
    install_packages:
      - gcc
      - rsync
      - git
      - epel-release
      - libffi-devel  # depended by python cffi, python cryptography
      - openssl-devel  # depended by python cryptography
      - libxslt-devel  # depended by lxml
      - supervisor

    autostart_services:
      - supervisord


- hosts: controllers
  tasks:
    - yum: name={{ item }} state=present
      with_items: install_packages

    - service: name={{ item }} enabled=yes state=started
      with_items: autostart_services

  vars:
    install_packages:
      - httpd
      - mod_wsgi
      - memcached
      - python-memcached

    autostart_services:
      - memcached

- hosts: networks
  tasks:
    - yum: name=http://rdo.fedorapeople.org/openstack-kilo/rdo-release-kilo.rpm state=present

    - yum: name={{ item }} state=present
      with_items: install_packages

    - service: name={{ item }} enabled=yes state=started
      with_items: autostart_services

  vars:
    install_packages:
      - openvswitch
      - dnsmasq

    autostart_services:
      - openvswitch

- hosts: computes
  tasks:
    - yum: name=http://rdo.fedorapeople.org/openstack-kilo/rdo-release-kilo.rpm state=present

    - yum: name={{ item }} state=present
      with_items: install_packages

    - service: name={{ item }} enabled=yes state=started
      with_items: autostart_services

  vars:
    install_packages:
      - libvirt
      - libvirt-python
      - openvswitch

    autostart_services:
      - libvirtd
      - openvswitch
