---

- name: Upgrade packages
  hosts: all
  tasks:
    - name: Upgrade packages
      yum: name=* state=latest
      when: upgrade is defined


- hosts: all
  tasks:
    - yum: name={{ item }} state=present
      with_items: install_packages

    - service: name={{ item }} enabled=yes state=started
      with_items: autostart_services

  vars:
    install_packages:
      - rsync
      - git
      - epel-release
      - supervisor

    autostart_services:
      - supervisord


- hosts: controller
  tasks:
    - yum: name={{ item }} state=present
      with_items: install_packages

    - service: name={{ item }} enabled=yes state=started
      with_items: autostart_services

  vars:
    install_packages:
      - httpd
      - mod_wsgi
      - memcached
      - python-memcached
      - libffi-devel  # depended by python cffi, python cryptography
      - openssl-devel  # depended by python cryptography
      - libxslt-devel  # depended by lxml

    autostart_services:
      - memcached

- hosts: computes
  tasks:
    - yum: name={{ item }} state=present
      with_items: install_packages

    - service: name={{ item }} enabled=yes state=started
      with_items: autostart_services

  vars:
    install_packages:
      - libvirt

    autostart_services:
      - libvirtd
