---

- name: Setup python virtualenv
  hosts: all
  tasks:
    - yum: name=python-virtualenv state=present

    - shell: source {{ virtualenv_dir }}/bin/activate
      register: venv_exists
      ignore_errors: True

    - shell: virtualenv --system-site-packages {{ virtualenv_dir }}
      when: venv_exists|failed

    - lineinfile: dest=~/.bashrc regexp="source.+activate" line="source {{ virtualenv_dir }}/bin/activate" create=yes

    - lineinfile: dest=~/.bashrc regexp="no_proxy" line="export no_proxy=localhost,127.0.0.1,controller,network,compute-1"
    - lineinfile: dest=~/.bashrc regexp="NO_PROXY" line="export NO_PROXY=localhost,127.0.0.1,controller,network,compute-1"

  vars_files:
    - vars/openstack.yml

- name: Pip install packages
  hosts: all
  tasks:
    - shell: pip install {{ item }}
      with_items:
        - tox
