---

keystone_admin_port: 35357
keystone_service_port: 5000

keystone_admin_url: http://controller:{{ keystone_admin_port }}/v2.0
keystone_service_url: http://controller:{{ keystone_service_port }}/v2.0
